/* =========================================
   MCN ADMIN LOADER V8 (AI INTEGRATED)
========================================= */

(async function () {

  console.log("🧠 MCN Boot V8 starting...");

  const loaded = {};

  async function safeImport(path) {
    try {
      const mod = await import(path);
      loaded[path] = true;
      console.log("✅ Loaded:", path);
      return mod;
    } catch (e) {
      loaded[path] = false;
      console.error("❌ Failed:", path, e);
      return null;
    }
  }

  /* =========================================
     GLOBAL MONITOR LOGGER
  ========================================= */

  window.logToMonitor = function (msg, type = "ok") {
    const box = document.getElementById("monitor");
    if (!box) return;

    const div = document.createElement("div");

    div.style.color =
      type === "error" ? "red" :
      type === "warn" ? "orange" :
      "#00ff88";

    div.textContent =
      `[${new Date().toLocaleTimeString()}] ${msg}`;

    box.appendChild(div);
    box.scrollTop = box.scrollHeight;
  };

  /* =========================================
     CORE MODULES
  ========================================= */

  await safeImport("./firebase.js");

  const authModule = await safeImport("./admin-auth.js");
  const controlModule = await safeImport("./admin-control.js");
  const monitorModule = await safeImport("./admin-monitor.js");

  /* MAIN ADMIN LOGIC */
  const adminModule = await safeImport("./admin/admin.js");

  /* AI ENGINE (LEVEL 2 SYSTEM) */
  const aiModule = await safeImport("./admin/ai-engine.js");

  await safeImport("./emergency-control.js");

  try {
    await safeImport("./admin-chat.js");
  } catch (e) {
    console.warn("⚠ Optional chat module missing");
  }

  /* =========================================
     START MONITOR ENGINE
  ========================================= */

  if (monitorModule?.startMonitor) {
    monitorModule.startMonitor();
    console.log("🖥 Monitor engine started");
  }

  /* =========================================
     AI ENGINE GLOBAL WRAPPER
  ========================================= */

  window.MCN_AI = aiModule || {};

  window.generateAIArticleGlobal = async function (topic) {

    if (aiModule?.generateAIArticle) {
      return await aiModule.generateAIArticle(topic);
    }

    return `
# ${topic}

⚠ AI ENGINE NOT LOADED

Fallback content generated by MCN system.
    `.trim();
  };

  window.autoGenerateBlogGlobal = async function (topic) {

    if (aiModule?.autoGenerateBlog) {
      return await aiModule.autoGenerateBlog(topic);
    }

    logToMonitor("⚠ AI auto engine missing", "warn");
  };

  /* =========================================
     UI FALLBACK FUNCTIONS
  ========================================= */

  window.generateAI = async function () {

    const topic = document.getElementById("aiTopic")?.value;
    if (!topic) return alert("Enter topic");

    logToMonitor("🤖 Generating AI article...");

    const article = await window.generateAIArticleGlobal(topic);

    alert(article);

    logToMonitor("✅ AI article generated");
  };

  window.autoPublishBlog = async function () {

    const topic = document.getElementById("aiTopic")?.value;
    if (!topic) return logToMonitor("Missing topic", "warn");

    logToMonitor("🚀 Auto publishing blog...");

    const post = await window.autoGenerateBlogGlobal(topic);

    logToMonitor("📝 Published: " + (post?.title || topic));
  };

  /* =========================================
     BLOG CREATOR (SAFE BRIDGE TO admin.js)
  ========================================= */

  window.createBlog = async function () {

    const title = document.getElementById("blogTitle")?.value;
    let content = document.getElementById("blogContent")?.value;
    const image = document.getElementById("blogImage")?.value;

    if (!title) return logToMonitor("Missing title", "error");

    if (!content || content.trim() === "") {
      content = await window.generateAIArticleGlobal(title);
    }

    if (adminModule?.createBlog) {

      adminModule.createBlog({
        title,
        content,
        image
      });

    } else {
      logToMonitor("⚠ Admin module not ready", "error");
    }
  };

  /* =========================================
     TRENDING SYSTEM (UI)
  ========================================= */

  window.loadTrending = async function () {

    const box = document.getElementById("trendingBox");
    if (!box) return;

    const trends = [
      "AI in 2026",
      "Nigeria tech boom",
      "Crypto adoption Africa",
      "Remote jobs explosion",
      "Creator monetization wave"
    ];

    box.innerHTML = "";

    trends.forEach(t => {
      box.innerHTML += `
        <div class="item" onclick="selectTrend('${t}')">
          🔥 ${t}
        </div>
      `;
    });

    logToMonitor("🔥 Trends loaded");
  };

  window.selectTrend = function (topic) {
    const input = document.getElementById("aiTopic");
    if (input) input.value = topic;

    logToMonitor("🔥 Selected: " + topic);
  };

  /* =========================================
     AI SETTINGS
  ========================================= */

  window.applyAISettings = function () {

    const provider = document.getElementById("aiProvider")?.value;

    if (window.AI_CONFIG) {
      window.AI_CONFIG.provider = provider;
    }

    logToMonitor("⚙ AI provider set: " + provider);
  };

  /* =========================================
     DEBUG REPORT
  ========================================= */

  console.log("📦 MODULE LOAD REPORT:", loaded);

  /* =========================================
     READY SIGNAL
  ========================================= */

  setTimeout(() => {
    console.log("🚀 MCN ENGINE FULLY READY");
    logToMonitor("🚀 MCN ENGINE FULLY READY");

    window.dispatchEvent(new Event("mcn-ready"));
  }, 1200);

})();