import { auth, db } from "./firebase.js";

import {
  onAuthStateChanged
} from "https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js";

import {
  doc,
  getDoc,
  addDoc,
  collection,
  onSnapshot,
  deleteDoc,
  updateDoc,
  query,
  orderBy,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";

import { watchControls, setControl } from "./admin-control.js";
import { initAdminGuard } from "./admin-auth.js";

/* =========================================
   GLOBAL EXPOSE
========================================= */

const expose = (name, fn) => {
  window[name] = fn;
};

/* =========================================
   LOG SYSTEM
========================================= */

function log(msg, type = "ok") {

  const box = document.getElementById("monitor");
  if (!box) return;

  const div = document.createElement("div");

  div.style.color =
    type === "error" ? "red" :
    type === "warn" ? "orange" :
    "#00ff88";

  div.textContent =
    `[${new Date().toLocaleTimeString()}] ${msg}`;

  box.appendChild(div);
  box.scrollTop = box.scrollHeight;
}

/* =========================================
   CONTROL STATE
========================================= */

window.MCN_CONTROLS = {
  featuredPostId: null,
  sponsoredPostId: null,
  adsEnabled: true,
  discoverEnabled: true
};

/* =========================================
   CONTROL WATCHER
========================================= */

watchControls((data = {}) => {

  window.MCN_CONTROLS = {
    featuredPostId: data.featuredPostId ?? null,
    sponsoredPostId: data.sponsoredPostId ?? null,
    adsEnabled: data.adsEnabled ?? true,
    discoverEnabled: data.discoverEnabled ?? true
  };

  log("📡 Control system synced");
});

/* =========================================
   ADMIN AUTH
========================================= */

initAdminGuard((user) => {

  log("✅ Secure admin verified");

  window.MCN_READY = true;
  window.MCN_ADMIN = user;

  loadPosts();
  loadAds();
});

/* =========================================
   SAFE CONTROL WRAPPER
========================================= */

async function safeControl(key, value) {
  try {
    await setControl(key, value);
    log(`⚙ ${key} updated`);
  } catch (err) {
    console.error(err);
    log("Control update failed", "error");
  }
}

/* =========================================
   CONTROL FUNCTIONS
========================================= */

window.setFeatured = async () => {
  const id = document.getElementById("featurePostId")?.value;
  if (!id) return log("Missing featured ID", "warn");
  await safeControl("featuredPostId", id);
};

window.setSponsored = async () => {
  const id = document.getElementById("sponsorPostId")?.value;
  const slot = document.getElementById("sponsorSlot")?.value;
  if (!id) return log("Missing sponsor ID", "warn");
  await safeControl("sponsoredPostId", { id, slot });
};

window.toggleAds = async () => {
  const current = window.MCN_CONTROLS?.adsEnabled ?? true;
  await safeControl("adsEnabled", !current);
};

window.toggleDiscover = async () => {
  const current = window.MCN_CONTROLS?.discoverEnabled ?? true;
  await safeControl("discoverEnabled", !current);
};

window.refreshSystem = () => {
  log("🔄 System refreshed");

  const box = document.getElementById("controlStatus");
  if (!box) return;

  const c = window.MCN_CONTROLS || {};

  box.innerHTML = `
    <div class="item">🧠 SYSTEM ONLINE</div>
    <div class="item">⭐ FEATURED: ${c.featuredPostId || "None"}</div>
    <div class="item">💰 SPONSORED: ${c.sponsoredPostId?.id || "None"} (${c.sponsoredPostId?.slot || "-"})</div>
    <div class="item">📢 ADS: ${c.adsEnabled ? "ON" : "OFF"}</div>
    <div class="item">🔍 DISCOVER: ${c.discoverEnabled ? "ON" : "OFF"}</div>
  `;
};

/* =========================================
   🤖 AI BLOG ENGINE
========================================= */

async function generateAIArticle(topic) {

  log("🤖 AI generating article...");

  return `
# ${topic}

## Introduction
This article was generated by MCN AI Engine.

## Overview
The topic "${topic}" is processed by AI logic.

## Key Points
- Insight 1 about ${topic}
- Insight 2 about ${topic}
- Insight 3 about ${topic}

## Conclusion
MCN AI successfully generated this content.
`.trim();
}

/* =========================================
   BLOG CREATION (AI POWERED)
========================================= */

window.createBlog = async function () {

  const title =
    document.getElementById("blogTitle")?.value;

  let content =
    document.getElementById("blogContent")?.value;

  const image =
    document.getElementById("blogImage")?.value;

  if (!title) return log("Missing blog title", "warn");

  if (!content || content.trim() === "") {
    content = await generateAIArticle(title);
  }

  try {

    await addDoc(collection(db, "posts"), {
      title,
      content,
      image: image || null,
      createdAt: serverTimestamp(),
      author: window.MCN_ADMIN?.uid || "admin",
      aiGenerated: true
    });

    log("📝 Blog published");

  } catch (err) {
    console.error(err);
    log("Blog publish failed", "error");
  }
};

/* =========================================
   AI PREVIEW
========================================= */

window.generateAI = async function () {

  const topic =
    document.getElementById("aiTopic")?.value;

  if (!topic) return alert("Enter topic");

  const article = await generateAIArticle(topic);

  alert(article);

  log("🤖 AI preview generated");
};

/* =========================================
   POSTS SYSTEM
========================================= */

let allPosts = [];

/* LOAD POSTS */
function loadPosts() {

  const box = document.getElementById("postsList");

  const q = query(collection(db, "posts"), orderBy("createdAt", "desc"));

  onSnapshot(q, (snap) => {

    allPosts = [];
    snap.forEach(d => allPosts.push({ id: d.id, ...d.data() }));

    renderPosts(allPosts);
  });
}

expose("loadPosts", loadPosts);

/* =========================================
   FIXED EDIT SYSTEM (INJECTED)
========================================= */

window.currentEditPostId = null;

window.loadIntoEditor = function (post) {

  window.currentEditPostId = post.id;

  document.getElementById("editPostId").value = post.id || "";
  document.getElementById("editPostTitle").value = post.title || "";
  document.getElementById("editPostContent").value = post.content || "";

  log("✏ Post loaded into editor");
};

window.updatePost = async function () {

  const id = window.currentEditPostId;

  const title = document.getElementById("editPostTitle")?.value;
  const content = document.getElementById("editPostContent")?.value;

  if (!id) return log("No post selected", "warn");

  try {

    await updateDoc(doc(db, "posts", id), {
      title,
      content,
      updatedAt: serverTimestamp()
    });

    log("✏ Post updated");

  } catch (err) {
    console.error(err);
    log("Update failed", "error");
  }
};

/* =========================================
   RENDER POSTS (UPDATED WITH EDIT)
========================================= */

function renderPosts(posts) {

  const box = document.getElementById("postsList");
  box.innerHTML = "";

  posts.forEach(p => {

    const safe = JSON.stringify(p).replace(/"/g, '&quot;');

    box.innerHTML += `
      <div class="item">

        <b>${p.title}</b><br>

        <small>${p.aiGenerated ? "🤖 AI POST" : "✍ Manual"}</small><br><br>

        <button onclick='loadIntoEditor(${safe})'>
          Edit
        </button>

        <button onclick="deletePost('${p.id}')">
          Delete
        </button>

      </div>
    `;
  });
}

/* DELETE */
window.deletePost = async (id) => {
  await deleteDoc(doc(db, "posts", id));
  log("🗑 Deleted post");
};

/* =========================================
   ADS SYSTEM
========================================= */

function loadAds() {

  const box = document.getElementById("upgradeList");

  onSnapshot(collection(db, "adRequests"), (snap) => {

    box.innerHTML = "";

    snap.forEach(d => {

      box.innerHTML += `
        <div class="item">
          <b>${d.data().title}</b><br>
          <button onclick="acceptAd('${d.id}')">Accept</button>
          <button onclick="rejectAd('${d.id}')">Reject</button>
        </div>
      `;
    });

  });
}

expose("loadAds", loadAds);

window.acceptAd = async (id) => {
  await updateDoc(doc(db, "adRequests", id), { status: "accepted" });
  log("✅ Ad accepted");
};

window.rejectAd = async (id) => {
  await updateDoc(doc(db, "adRequests", id), { status: "rejected" });
  log("❌ Ad rejected");
};