import { db } from "./firebase.js";

import {
  collection,
  addDoc,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";

/* =========================================
   MCN LEVEL 2 AI ENGINE
========================================= */

/* 🔑 PUT YOUR API KEY HERE LATER */
const AI_CONFIG = {
  provider: "mock", // "openai" | "gemini" | "mock"
  apiKey: ""
};

/* =========================================
   1. TRENDING TOPIC ENGINE (MOCK)
========================================= */

export async function getTrendingTopics() {

  // Later replace with real scraping API
  return [
    "AI in 2026",
    "Nigeria tech startups",
    "Cryptocurrency trends",
    "Social media monetization",
    "Remote jobs explosion"
  ];
}

/* =========================================
   2. SEO OPTIMIZER
========================================= */

function generateSEO(title, content) {

  const keywords = title
    .toLowerCase()
    .split(" ")
    .filter(w => w.length > 3);

  return {
    keywords: keywords.join(", "),
    description: content.slice(0, 150),
    slug: title.toLowerCase().replace(/\s+/g, "-")
  };
}

/* =========================================
   3. AI CONTENT ENGINE (CORE)
========================================= */

export async function generateAIArticle(topic) {

  if (AI_CONFIG.provider === "mock") {

    return `
# ${topic}

## Introduction
This article was generated by MCN Level 2 AI Engine.

## Main Insights
- ${topic} is trending globally
- AI automation is increasing
- Monetization opportunities are growing

## Conclusion
MCN Engine successfully generated structured content.
    `.trim();
  }

  /* OPENAI READY HOOK */
  if (AI_CONFIG.provider === "openai") {

    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${AI_CONFIG.apiKey}`
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content: "You are a professional SEO blog writer."
          },
          {
            role: "user",
            content: `Write a detailed SEO blog about: ${topic}`
          }
        ]
      })
    });

    const data = await res.json();
    return data.choices[0].message.content;
  }

  return "AI provider not configured";
}

/* =========================================
   4. AUTO IMAGE GENERATION (HOOK)
========================================= */

export async function generateImage(topic) {

  // Placeholder (plug DALL·E / Stability AI here)
  return `https://source.unsplash.com/800x600/?${encodeURIComponent(topic)}`;
}

/* =========================================
   5. MONETIZATION LAYER (AUTO ADS / AFFILIATES)
========================================= */

function injectMonetization(content) {

  return content +
`

---

💰 Sponsored Links:
- Best hosting for creators → example.com
- AI tools for bloggers → example.com

`;
}

/* =========================================
   6. FULL AUTO BLOG GENERATOR
========================================= */

export async function autoGenerateBlog(topic) {

  const content = await generateAIArticle(topic);

  const seo = generateSEO(topic, content);
  const image = await generateImage(topic);

  const finalContent = injectMonetization(content);

  const post = {
    title: topic,
    content: finalContent,
    image,
    seo,
    aiGenerated: true,
    createdAt: serverTimestamp(),
    status: "auto-published"
  };

  await addDoc(collection(db, "posts"), post);

  return post;
}

/* =========================================
   7. AUTO SCHEDULER (OPTIONAL LOOP HOOK)
========================================= */

export async function scheduleAutoPost(topic, delayMs = 60000) {

  setTimeout(async () => {

    await autoGenerateBlog(topic);

    console.log("🚀 Auto post published:", topic);

  }, delayMs);
}

/* =========================================
   EXPORT READY
========================================= */

console.log("🤖 MCN LEVEL 2 AI ENGINE LOADED");